Fix: lstsq compilation with complex<float> inputs  (#251)
This fix resolves a compilation error `gelsd.tcc:146:25: error: invalid
conversion from 'const float*' to 'cxxlapack::FLOAT_COMPLEX*'` when
linalg::lstsq is called with complex<float> arguments.
Note that `complex<double>` and other types were unaffected.

- A test case that demonstrates the issue is added to
test/test_linalg.cpp
- The fix adds const to the relevant interface to correctly match the
expected input data type
- The test compiles and passes with this fix

---------

Co-authored-by: Johan Mabille <johan.mabille@gmail.com>